---
Resources:
  DemoWebServerSG:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Allow access on ports 80 and 22
      GroupName: My Test WebServerSG
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 103.140.231.106/32
      Tags:
        - Key: Name
          Value: My Test WebServerSG
      VpcId: vpc-0004ec644e1c35014

  EC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: t2.micro
      SubnetId: subnet-062b436601432ce49
      SecurityGroupIds:
        - !Ref DemoWebServerSG
      KeyName: DemoKeyPair
      ImageId: ami-068e0f1a600cd311c
      Tags:
        - Key: Name
          Value: DemoWebServerEC2
      UserData:
        Fn::Base64:
          !Sub |
            #!/bin/bash -xe
            sudo su
            yum update -y
            yum install -y httpd
            cd /var/www/html
            wget https://github.com/azeezsalu/techmax/archive/refs/heads/main.zip
            unzip main.zip
            cp -r techmax-main/* /var/www/html/
            rm -rf techmax-main main.zip
            systemctl enable httpd 
            systemctl start httpd